env:
  - GO111MODULE=on
  - GOPROXY="https://proxy.golang.org,direct"

archives:
  - id: default
    wrap_in_directory: true

builds:
  - binary: wtfutil
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64

before:
  hooks:
    - make install

brews:
  - github:
      owner: wtfutil
      name: homebrew-wtfutil

    name: wtfutil
    homepage: 'https://wtfutil.com'
    description: 'The personal information dashboard for your terminal.'
