wtf:
  refreshInterval: 1
  bamboohr:
    refreshInterval: 900
    url: "https://api.bamboohr.com/api/gateway.php"
  gcal:
    eventCount: 10
    refreshInterval: 300
    secretFile: "~/.wtf/gcal/client_secret.json"
  git:
    commitCount: 10
    refreshInterval: 8
    repository: "/Users/chris/go/src/github.com/senorprogrammer/wtf"
  github:
    refreshInterval: 900
    repo: "core-api"
  jira:
    refreshInterval: 900
  opsgenie:
    refreshInterval: 21600
  security:
    refreshInterval: 3600
  status:
    refreshInterval: 1
  weather:
    cityId: 6173331
    language: "EN"
    tempUnit: "C"
    refreshInterval: 900
